services:
  postgres:
    image: postgres:17.0
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    restart: always 
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h localhost -p 5432 -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - main

  adminer:
    image: adminer:4.8.1
    container_name: adminer
    restart: always
    ports:
      - "8089:8080"
    networks:
      - main

  minio:
    container_name: minio
    image: minio/minio
    command: minio server --console-address ":9001" /data
    restart: always 
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data/minio_data:/data
    networks:
      - main

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis_data:/data
    networks:
      - main

networks:
  main:
    driver: bridge
